#!/bin/bash

OUTPUT_FILE="asm_test_log.out"

#sed -i '' -e "s/DIR_LAB/%:l1/g" 		test.s
#sed -i '' -e "s/IND_LAB/:l1/g" 		test.s
#sed -i '' -e "s/DIR/%1985229328/g" 	test.s 	
#sed -i '' -e "s/IND/4660/g" 			test.s 
#sed -i '' -e "s/REG/r14/g" 			test.s

# COLORS #

RED="\033[1;31m"
GRN="\033[1;32m"
YEL="\033[1;33m"
BLU="\033[1;34m"
MAG="\033[1;35m"
CYN="\033[1;36m"
WHT="\033[1;37m"
RESET="\033[0m"

# DIFF REF_ASM VS MY_ASM

make -C ..
cp ../asm bin/asm

rm -f champs/*.cor

for file in champs/*; do
	if echo $file | grep "\.s" &>/dev/null; then

		file=$(echo $file | sed "s/\.s//")

		./bin/asm $file.s &> /dev/null
		mine=$(echo $file | sed "s/$/_mine.cor/")
		if [ -f $file.cor ]; then
			mv $file.cor $mine
		fi

		./bin/asm_ref $file.s &> /dev/null
		ref=$(echo $file | sed "s/$/_ref.cor/")
		if [ -f $file.cor ]; then
			mv $file.cor $ref
		fi

		if [ ! -f $ref ]; then
			printf $MAG
			echo -e "$(echo $file.s | awk -F/ '{print $NF}') : no output for ref"
		elif [ ! -f $mine ]; then
			printf $MAG
			echo -e "$(echo $file.s | awk -F/ '{print $NF}') : no output for mine"
		elif ! diff -q $ref $mine &> /dev/null; then
			printf $RED
			echo -e "$(echo $file.s | awk -F/ '{print $NF}') : diff between mine and ref"
			hexdump -C $ref > tmp1
			hexdump -C $mine > tmp2
			diff tmp1 tmp2 >> $OUTPUT_FILE
			printf "\n\n" >> $OUTPUT_FILE
			rm -f tmp1 tmp2
		else
			printf $BLU
			echo -e "$(echo $file.s | awk -F/ '{print $NF}') : no diff"
		fi

	fi
	printf $RESET
done

rm -f champs/*.cor
