#!/bin/bash -i

CHAMP_DIR="champs"
COR_DIR="champs/cor"
LOG_DIR="logs"

# COLORS #

RED="\033[1;31m"
GRN="\033[1;32m"
YEL="\033[1;33m"
BLU="\033[1;34m"
MAG="\033[1;35m"
CYN="\033[1;36m"
WHT="\033[1;37m"
RESET="\033[0m"

# STARTUP #

COR_REF="./bin/corewar_ref"
COR_MINE="./bin/corewar"
ASM_REF="./bin/asm_ref"
ASM_MINE="./bin/asm"

make -C ..
mkdir -p champs/cor
mkdir -p $LOG_DIR
cp ../corewar $COR_MINE
cp ../asm $ASM_MINE

# COMPILE CHAMP LIST #

while true; do
	read -e -p "Compile Champions ? " yn
	case $yn in
		[Yy]* )
			ls -1 $CHAMP_DIR | grep "\.s" | sed -e "s/\.s//g" > tmp
			while read -r line; do
				$ASM_REF $CHAMP_DIR/$line.s
				mv $CHAMP_DIR/$line.cor $COR_DIR/$line.cor
			done < tmp
			break;;
		[Nn]* ) break;;
	esac
done

rm -f tmp

clear

# AFF CHAMP LIST #

cd $COR_DIR

CURSOR_X=0
CURSOR_Y=0
MAX_Y=20

clear 
printf $BLU
for file in *; do
	tput cup $CURSOR_Y $CURSOR_X 
	echo $file
	CURSOR_Y=$(($CURSOR_Y + 1))
	if [[ $CURSOR_Y -eq $MAX_Y ]]; then
		CURSOR_Y=0
		CURSOR_X=$(($CURSOR_X + 30))
	fi
done

printf $RESET
tput cup $MAX_Y 0

# ARGS #

echo ""
printf $WHT
read -e -p "Champion 1            : " C1
read -e -p "Champion 2            : " C2
read -e -p "Champion 3            : " C3
read -e -p "Champion 4            : " C4
read -e -p "Start at cycle        : " START_CYCLE
read -e -p "Cycles [empty = inf.] : " NUM_CYCLE
printf $RESET

# RUN #

cd ../..

LOG_NAME="$LOG_DIR/$(echo $C1 | sed "s/\.cor/\./")$(echo $C2 | sed "s/\.cor/\./")$(echo $C3 | sed "s/\.cor/\./")$(echo $C4 | sed "s/\.cor/\./")log"

REF_CMD="$COR_REF -d CYCLE"
MY_CMD="$COR_MINE -d CYCLE"

if [[ ${#C1} -ge 1 ]]; then
	REF_CMD="$REF_CMD $COR_DIR/$C1"
	MY_CMD="$MY_CMD $COR_DIR/$C1"
fi
if [[ ${#C2} -ge 1 ]]; then
	REF_CMD="$REF_CMD $COR_DIR/$C2"
	MY_CMD="$MY_CMD $COR_DIR/$C2"
fi
if [[ ${#C3} -ge 1 ]]; then
	REF_CMD="$REF_CMD $COR_DIR/$C3"
	MY_CMD="$MY_CMD $COR_DIR/$C3"
fi
if [[ ${#C4} -ge 1 ]]; then
	REF_CMD="$REF_CMD $COR_DIR/$C4"
	MY_CMD="$MY_CMD $COR_DIR/$C4"
fi

if [[ ! ${#NUM_CYCLE} -ge 1 ]]; then
	NUM_CYCLE=2147483647
fi

if [[ ! ${#START_CYCLE} -ge 1 ]]; then
	START_CYCLE=1
fi

i=0

clear

printf $WHT
printf "$C1 $C2 $C3 $C4\n"
printf $RESET

while [[ $i -le $NUM_CYCLE ]]; do
	tput cup 1 1
	CURRENT_CYCLE=$(($START_CYCLE + $i))
	printf "$CURRENT_CYCLE\n"
	REF_OUT=$(echo $REF_CMD | sed "s/CYCLE/$CURRENT_CYCLE/")
	MY_OUT=$(echo $MY_CMD | sed "s/CYCLE/$CURRENT_CYCLE/")
	if ! cmp <($REF_OUT) <($MY_OUT) &>/dev/null; then
		printf $RED
		printf "Diff KO at cycle $CURRENT_CYCLE (Logged to $LOG_NAME)\n"
		diff <($REF_OUT) <($MY_OUT) &> $LOG_NAME
		printf $RESET
		exit
	fi
	if $REF_OUT | grep "won" &>/dev/null; then
		printf $BLU
		$REF_OUT | grep "won"
		printf $RESET
		printf "Diff OK\n" > $LOG_NAME
		exit
	fi
	i=$(($i + 1))
done
