#!/bin/bash

BASE_DIR="./"
LOG_DIR="logs"
COR_REF="./bin/corewar_ref"
COR_MINE="./bin/corewar"
ASM_REF="./bin/asm_ref"
ASM_MINE="./bin/asm"
CHAMP_DIR="champs"
COR_DIR="champs/cor"
LOG_DIR="logs"

cd $BASE_DIR
make -C ..
mkdir -p $COR_DIR
mkdir -p $LOG_DIR
rm -f $LOG_DIR/*
cp ../corewar $COR_MINE
cp ../asm $ASM_MINE

ls -1 $CHAMP_DIR | grep "\.s" | sed -e "s/\.s//g" > tmp

while true; do
	read -e -p "Compile Champions ? " yn
	case $yn in
		[Yy]* )
			ls -1 $CHAMP_DIR | grep "\.s" | sed -e "s/\.s//g" > tmp
			while read -r line; do
				$ASM_REF $CHAMP_DIR/$line.s
				mv $CHAMP_DIR/$line.cor $COR_DIR/$line.cor
			done < tmp
			break;;
		[Nn]* ) break;;
	esac
done

rm -f tmp

clear
