#!/bin/bash

MAIN_DIR="./"
AUTO_DIR="./auto/"
CHAMP_DIR="champs"
COR_DIR="champs/cor"
LOG_DIR="logs"
COR_REF="./bin/corewar_ref"
COR_MINE="./bin/corewar"
ASM_REF="./bin/asm_ref"
ASM_MINE="./bin/asm"

# FUNCTION #

print_progress () {
	printf "[$(ls -1 $LOG_DIR | wc -l | tr -d '\t' | tr -d ' ')/$(cat $AUTO_DIR/total.out)] "
}

# RUN #

cd $MAIN_DIR

C1=$(echo $1 | awk -F"/" '{print $NF}')
C2=$(echo $2 | awk -F"/" '{print $NF}')
C3=$(echo $3 | awk -F"/" '{print $NF}')
C4=$(echo $4 | awk -F"/" '{print $NF}')

LOG_NAME="$LOG_DIR/$(echo $C1 | sed "s/\.cor/\./")$(echo $C2 | sed "s/\.cor/\./")$(echo $C3 | sed "s/\.cor/\./")$(echo $C4 | sed "s/\.cor/\./")log"

REF_CMD="$COR_REF -d CYCLE"
MY_CMD="$COR_MINE -d CYCLE"

if [[ ${#1} -ge 1 ]]; then
	REF_CMD="$REF_CMD $1"
	MY_CMD="$MY_CMD $1"
fi
if [[ ${#2} -ge 1 ]]; then
	REF_CMD="$REF_CMD $2"
	MY_CMD="$MY_CMD $2"
fi
if [[ ${#3} -ge 1 ]]; then
	REF_CMD="$REF_CMD $3"
	MY_CMD="$MY_CMD $3"
fi
if [[ ${#4} -ge 1 ]]; then
	REF_CMD="$REF_CMD $4"
	MY_CMD="$MY_CMD $4"
fi


if [[ -f $AUTO_DIR/auto.conf ]]; then
	NUM_CYCLE=$(cat $AUTO_DIR/auto.conf | grep "NUM_CYCLE" | cut -d '=' -f 2)
	START_CYCLE=$(cat $AUTO_DIR/auto.conf | grep "START_CYCLE" | cut -d '=' -f 2)
else
	NUM_CYCLE=2147483647
	START_CYCLE=1
fi

i=0

NAMES="$C1 $C2 $C3 $C4"
printf "Launched $NAMES\n"

while [[ $i -le $NUM_CYCLE ]]; do
	CURRENT_CYCLE=$(($START_CYCLE + $i))
	REF_OUT=$(echo $REF_CMD | sed "s/CYCLE/$CURRENT_CYCLE/")
	MY_OUT=$(echo $MY_CMD | sed "s/CYCLE/$CURRENT_CYCLE/")
	if ! cmp <($REF_OUT) <($MY_OUT) &>/dev/null; then
		diff <($REF_OUT) <($MY_OUT) > $LOG_NAME
		print_progress
		printf "Diff KO at cycle $CURRENT_CYCLE | $NAMES\n"
		printf "Diff KO at cycle $CURRENT_CYCLE\n___\n\n" > $LOG_NAME
		exit
	fi
	if $REF_OUT | grep "won" &>/dev/null; then
		printf "Diff OK | Game ended at cycle $CURRENT_CYCLE\n" > $LOG_NAME
		print_progress
		printf "$($REF_OUT | grep "won" | sed "s/\n//") | $NAMES\n"
		exit
	fi
	i=$(($i + 1))
done

printf "Diff OK | Stopped at cycle $CURRENT_CYCLE\n" > $LOG_NAME
print_progress
printf "Stopped at cycle $CURRENT_CYCLE | Diff OK | $NAMES\n"
